name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  firebase_app_check: ^0.2.2+5
  firebase_auth: ^4.19.5
  firebase_database: ^10.5.5
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/voz_claralogo_4.png
  - assets/vectors/corner_up_left_2_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/container_1_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/container_x2.svg
  - assets/images/hud_camera_1.png
  - assets/images/qr_code_afinz_1.png
  - assets/images/voz_claralogo_4.png
  - assets/vectors/mail_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/corner_up_left_3_x2.svg
  - assets/images/voz_claralogo_4.png
  - assets/vectors/book_4_x2.svg
  - assets/vectors/book_6_x2.svg
  - assets/vectors/corner_up_left_1_x2.svg
  - assets/vectors/book_2_x2.svg
  - assets/vectors/book_1_x2.svg
  - assets/vectors/book_8_x2.svg
  - assets/vectors/book_3_x2.svg
  - assets/vectors/book_7_x2.svg
  - assets/vectors/book_5_x2.svg
  - assets/vectors/book_x2.svg
  - assets/images/image_1.png
  - assets/vectors/mic_x2.svg
  - assets/vectors/corner_up_left_x2.svg
  - assets/images/voz_claralogo_4.png
  - assets/images/voz_claralogo_4.png
  - assets/vectors/super_g_x2.svg
  - assets/vectors/shape_1_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/facebook_x2.svg

